before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/tse-download/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''

    # Templates of the Docker image names.
    image_templates:
      - "empire/go-tse:latest"
      - "empire/go-tse:{{ .Tag }}"
      - "empire/go-tse:v{{ .Major }}"

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Defaults to false.
    skip_push: false

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

    # Whether to use `docker buildx build` instead of `docker build`.
    # You probably want to set it to true when using flags like `--platform`.
    # If true, will also add `--load` to the build flags.
    # Defaults to false.
    use_buildx: true

    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
