before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/tse-download/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - image_templates:
      - 'ghcr.io/empire/go-tse:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    goarm: ''
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  http://github.com/empire/go-tse
    description: Download tickers from tse
    maintainer: Hossein Zolfi <hossein.zolfi@gmail.com>
    license: MIT
    vendor: Go-Tse
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - golang
